name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare main.py
      run: |
        if [ -f apk.py ]; then
          mv apk.py main.py
        fi

    - name: Build with Buildozer
      uses: ArtemSydoryk/buildozer-action@v1.2
      with:
        command: buildozer -v android debug
        subpath: '.'

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
